### PR TITLE
Updating to conform with new naming standards.

### PR DESCRIPTION
**Pull request by mcallan-sf**
Code Changes
- Updates the names of the DataRaptors and the Integration Procedures to conform with new naming standards. 
- Extends names which are now truncated less in the template sheet in order to keep formula consistent.
- Updates a dated apex class interface. 

Template Changes
- Update Settings tab to use new names
- Update tab names to match
- Added deployment steps/stage tab for easily jumping to tabs in order

Sharing a template with the changes applied. Have tested the original changes with a client but haven't test run the new template. Named assuming 1.4. 
[Vlocity.EPC on Steroids.Offering Catalog Bootstrap-20241025-1.4-Release](https://docs.google.com/spreadsheets/d/11tJ8lrzEhO0kJffsBBumpr6zcIWlpoGB5no6Xf23OfI/edit?gid=588297765#gid=588297765)

### CODE REVIEW

**Review by sashavmorozov — APPROVED** [review]

**Review by sashavmorozov — APPROVED** [review]
Thank you, good person from Internet 🌠

**Comment by sashavmorozov** [comment]
Kind sir, appreciate your suggestion and implementation, you are a hero 🙏
@mcallan-sf, could you share the EOS spreadsheet as "View for anybody with a link" so that I can post it into the release notes?

**Comment by mcallan-sf** [comment]
@sashavmorozov I'm a madam not a sir, but I appreciate your formal thanks. I've given you access to the sheet to make a copy. As it's on my work profile I'd have to share it with each individual outside the org so ideally there's a copy somewhere more public/associated with this repo.

**Comment by sashavmorozov** [comment]
Apologies for that 🙇‍♂️

**Pull request merged**
